[BP-81] Notion - detect tasks from integration
timecamp-org/timecamp-browser-plugin pull request #118
Opened 2024-01-11 14:02 UTC by bpDevTc

2024-01-11 14:43 UTC, owojno-timecamp requested changes

2024-01-11 14:43 UTC, owojno-timecamp commented on scripts-2.0/third_party/notion.js
> +        const titleElement = elem.querySelectorAll('.notion-scroller .notion-page-block')[0] ?? null;
a czemu już nie querySelector, żeby zwrócić pierwszy tylko szukasz całej tablicy?

2024-01-11 14:43 UTC, owojno-timecamp commented on scripts-2.0/third_party/notion.js
> +        const titleElement = elem.parentElement.parentElement.parentElement.querySelectorAll('.notion-selectable')[0] ?? null;
jw

2024-01-11 15:19 UTC, bpDevTc commented on scripts-2.0/third_party/notion.js
> +        const titleElement = elem.querySelectorAll('.notion-scroller .notion-page-block')[0] ?? null;
done

2024-01-11 15:21 UTC, owojno-timecamp submitted a review, later dismissed

2024-01-16 06:49 UTC, owojno-timecamp approved these changes

2024-01-16 07:52 UTC, merged