Add SmartSheet integration
timecamp-org/timecamp-browser-plugin pull request #127
Opened 2024-01-25 08:20 UTC by u-can-do-it

https://timecampdev.atlassian.net/jira/software/c/projects/BP/boards/40?selectedIssue=BP-85

2024-01-25 09:24 UTC, owojno-timecamp requested changes
drobnica

2024-01-25 09:24 UTC, owojno-timecamp commented on scripts-2.0/style/main.scss
```suggestion
@import 'common';
@import 'reset-styles';

```
chyba nie mamy lintera tu podpiętego, ale mamy ustalone, że importy w pojedynczych cudzysłowach

2024-01-25 09:24 UTC, owojno-timecamp commented on scripts-2.0/third_party/smartsheet.js
> +      }
```suggestion
      if (taskName === alreadyCreatedButton.title) {
        return false;
      }
      alreadyCreatedButton.remove();
```

2024-01-25 09:24 UTC, owojno-timecamp commented on scripts-2.0/third_party/smartsheet.js
> +      } else {
niepotrzebny else. I Tak uciekasz jeśli wejdzie w ifa

2024-04-04 10:06 UTC, bpDevTc approved these changes

2024-04-15 12:00 UTC, owojno-timecamp approved these changes

2024-04-15 12:00 UTC, merged