[TCD-1656] Show instruction page after install or update to 2.21.1
timecamp-org/timecamp-browser-plugin pull request #30
Opened 2021-07-20 14:07 UTC by kamilbator

[TCD-1656](https://timecampdev.atlassian.net/browse/TCD-1656)

2021-07-21 05:57 UTC, owolanin-timecamp requested changes

2021-07-21 05:57 UTC, owolanin-timecamp commented on scripts-2.0/background.js
> +        let versionWhenActionIsPerformed = '2.21.1';
```suggestion
        const thisVersion = browser.runtime.getManifest().version;
        const versionWhenActionIsPerformed = '2.21.1';
```

2021-07-26 07:15 UTC, kamilbator commented on scripts-2.0/background.js
> +        let versionWhenActionIsPerformed = '2.21.1';
Zrobione

2021-07-26 07:16 UTC, owolanin-timecamp approved these changes

2021-07-27 09:32 UTC, merged