Feat/tcd 1189 displaying errors
timecamp-org/timecamp-browser-plugin pull request #39
Opened 2021-08-10 07:44 UTC by kamilbator

[TCD-1189](https://timecampdev.atlassian.net/browse/TCD-1189)

2021-08-10 10:46 UTC, owojno-timecamp requested changes

2021-08-10 10:46 UTC, owojno-timecamp commented on scripts-2.0/components/ContextMenu/Error/NoInternetError/index.tsx
> +import imageSrc from "../../../../../images/no-internet.svg";
tu i we wszystkich innych wielokropkowych ścieżkach nie możemy jakoś zaczynać od roota projektu ?

2021-08-10 11:00 UTC, owojno-timecamp submitted a review, later dismissed

2021-08-13 09:38 UTC, owolanin-timecamp submitted a review, later dismissed

2021-08-18 08:14 UTC, owojno-timecamp approved these changes

2021-08-18 10:12 UTC, merged