[BP-3] changing date format for the timer
timecamp-org/timecamp-browser-plugin pull request #79
Opened 2022-09-30 12:23 UTC by chenten16

2022-10-03 12:54 UTC, bpDevTc approved these changes

2022-10-13 07:43 UTC, bpDevTc requested changes

2022-10-13 07:43 UTC, bpDevTc commented on scripts-2.0/components/PopupMenu/WorkingTimerSection/index.tsx
> +    const [durationFormat, setDurationFormat] = useState(DURATION_FORMATS.CLASSIC_WITH_SECONDS);
format should be changed to `DURATION_FORMATS.HHMMSS`
use `DEFAULT_FORMAT` from `scripts-2.0/TimeFormatter.js` (change it first :) )

2022-10-18 14:22 UTC, bpDevTc submitted a review, later dismissed

2022-10-19 09:24 UTC, owojno-timecamp approved these changes

2022-10-19 09:24 UTC, merged